#!/bin/bash

# Usage: ./run.sh <service_name> <release_version> <user_name>

SERVICE_NAME=$1
RELEASE_VERSION=$2
USER_NAME=$3

if [ -z "$SERVICE_NAME" ]; then
  echo "SERVICE_NAME is required"
  exit 1
fi 

if [ -z "$RELEASE_VERSION" ]; then
  echo "RELEASE_VERSION is required"
  exit 1
fi 

if [ -z "$USER_NAME" ]; then
  echo "USER_NAME is required"
  exit 1
fi 

git fetch --all && git checkout main

mkdir -p ./golang/${SERVICE_NAME}

PROTO_DIR=./proto/${SERVICE_NAME}
protoc --go_out=./golang/${SERVICE_NAME} \
--go-grpc_out=./golang/${SERVICE_NAME} \
--go_opt=paths=source_relative \
--go-grpc_opt=paths=source_relative \
--proto_path="$PROTO_DIR" \
"$PROTO_DIR"/*.proto

tree 

cd golang/${SERVICE_NAME}

go mod init github.com/${USER_NAME}/cocosette-proto/golang/${SERVICE_NAME} || true

go mod tidy

cd ../../

git add ./proto/${SERVICE_NAME}/* && git commit -am "🔄 Update grpc definition" || true

git add ./golang/${SERVICE_NAME}/${SERVICE_NAME}.pb.go && git commit -am "✨ Add autogenerated message code" || true

git add ./golang/${SERVICE_NAME}/${SERVICE_NAME}_grpc.pb.go && git commit -am "✨ Add autogenerated service code" || true

git add ./golang/${SERVICE_NAME}/go.mod && git commit -am "🔄 Update go.mod" || true

git add ./golang/${SERVICE_NAME}/go.sum && git commit -am "🔄 Update go.sum" || true

git push origin HEAD:main

git tag -fa golang/${SERVICE_NAME}/${RELEASE_VERSION} \
  -m "golang/${SERVICE_NAME}/${RELEASE_VERSION}" 
git push origin refs/tags/golang/${SERVICE_NAME}/${RELEASE_VERSION}
